select 
     a.DS_PLANO
    ,a.NR_PROTOCOLO_ANS
    ,a.CD_SCPA
    ,c.NR_SEQUENCIA
    ,c.DS_COBERTURA
from PLS_PLANO a
INNER JOIN PLS_COBERTURA b ON a.NR_SEQUENCIA = b.NR_SEQ_PLANO
INNER JOIN PLS_TIPO_COBERTURA c ON b.NR_SEQ_TIPO_COBERTURA = c.NR_SEQUENCIA
ORDER BY 4
;
