-- QUERY PARA BUSCAR CONTRATOS QUE ESTÃO COM STATUS DE ATIVOS, MAS SEM BENEFICIÁRIOS ATIVOS

SELECT *FROM PLS_CONTRATO WHERE NR_sEQUENCIA = '45273';
SELECT *FROM  PLS_SEGURADO WHERE CD_PESSOA_FISICA = '46801';



SELECT 
      NR_SEQUENCIA
      , CASE 
            WHEN CD_PF_ESTIPULANTE IS NULL THEN 
                (SELECT DS_RAZAO_SOCIAL FROM PESSOA_JURIDICA b WHERE a.CD_CGC_ESTIPULANTE = b.CD_CGC)
            ELSE (SELECT NM_PESSOA_FISICA FROM PESSOA_FISICA c WHERE a.CD_PF_ESTIPULANTE = c.CD_PESSOA_FISICA)
        END AS ESTIPULANTE
FROM PLS_CONTRATO a
WHERE IE_SITUACAO = '2' AND 
NR_SEQUENCIA NOT IN 
                (SELECT 
                    NR_SEQ_CONTRATO
                FROM PLS_SEGURADO
                WHERE  IE_SITUACAO_ATEND = 'A' OR IE_SITUACAO_ATEND = 'S'
                GROUP BY 
                    NR_SEQ_CONTRATO) -- SUBSELECT SELECIONA TODOS OS CONTRATOS QUE POSSUEM BENEFICIÁRIOS COM SITUAÇÃO ATIVA OU SUSPENSA
ORDER BY 1;
    
