SELECT 
     a.CD_PROCEDIMENTO AS COD_PROCEDIMENTO
    ,c.DS_PROCEDIMENTO AS DS_PROCEDIMENTO
    ,a.IE_ORIGEM_PROCED AS COD_ORIGEM
    , CASE a.IE_ORIGEM_PROCED
            WHEN 8 THEN 'TUSS' 
            WHEN 5 THEN 'CBHPM'
            WHEN 1 THEN 'AMB'
            WHEN 4 THEN 'PROPRIO'   
            END AS ORIGEM
    ,a.IE_COBERTURA AS LIBERACAO
    ,a.NR_SEQ_TIPO_COBERTURA AS COD_COBERTURA
    ,d.DS_COBERTURA AS DESC_COBERTURA
FROM PLS_COBERTURA_PROC a
INNER JOIN procedimento c ON a.CD_PROCEDIMENTO = c.CD_PROCEDIMENTO AND a.IE_ORIGEM_PROCED = c.IE_ORIGEM_PROCED
INNER JOIN PLS_TIPO_COBERTURA d ON a.NR_SEQ_TIPO_COBERTURA = d.NR_SEQUENCIA
WHERE EXISTS
    (
        SELECT CD_PROCEDIMENTO
        FROM PLS_COBERTURA_PROC b
        WHERE a.CD_PROCEDIMENTO = b.CD_PROCEDIMENTO
            AND a.NR_SEQ_TIPO_COBERTURA = b.NR_SEQ_TIPO_COBERTURA
            AND a.IE_ORIGEM_PROCED = b.IE_ORIGEM_PROCED
            AND a.IE_COBERTURA != b.IE_COBERTURA
    )
--AND NR_SEQ_TIPO_COBERTURA = '17' and a.CD_PROCEDIMENTO = '10101039'
ORDER BY 1, 3
;

